# Generated by Django 5.0.4 on 2024-05-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_employer_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer_profile',
            name='first_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='employer_profile',
            name='last_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
