# Generated by Django 5.0.4 on 2024-05-31 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_employer_profile_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employer_profile',
        ),
    ]
