# Generated by Django 5.0.4 on 2024-04-27 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_employee_employer_delete_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='userID',
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
