# Generated by Django 5.0.4 on 2024-04-28 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='employerID',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
