# Generated by Django 5.0.4 on 2024-04-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
