# Generated by Django 5.0.4 on 2024-04-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_job_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
