# Generated by Django 5.0.4 on 2024-04-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_job_feedback_job_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
