# Generated by Django 5.0.4 on 2024-04-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_alter_job_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
