# Generated by Django 5.0.4 on 2024-04-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_alter_job_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employer_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='employr_feedback',
            field=models.TextField(blank=True),
        ),
    ]
