# Generated by Django 5.0.4 on 2024-04-29 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_job_employer_rating_job_employr_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='employr_feedback',
            new_name='employer_feedback',
        ),
    ]
