# Generated by Django 5.0.4 on 2024-05-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_alter_job_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('IT', 'IT & Programming'), ('Design', 'Design & Creative'), ('Writing', 'Writing & Translation'), ('Admin', 'Admin Support'), ('Customer', 'Customer Support'), ('Sales', 'Sales & Marketing'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
