# Generated by Django 5.0.4 on 2024-05-17 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_job_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='rate',
        ),
        migrations.AddField(
            model_name='job',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='job',
            name='pay_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
