# Generated by Django 5.0.4 on 2024-05-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_remove_job_rate_job_attachment_job_pay_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
    ]
