# Generated by Django 5.0.4 on 2024-05-31 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_job_duration_job_needs_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='job',
            name='needs_review',
        ),
    ]
