# Generated by Django 5.0.4 on 2024-06-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0022_rename_feedback_job_employee_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employee_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='employer_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
